# -*- coding: utf-8 -*-
"""Base de dados exercicios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gp7I0TUdabLMA0PbXMgJcegQAJCE01pG

# **Base de dados exercicios**

1 - Utilizando comandos SQL, apresente a instrução que resolva os seguintes problemas propostos:
Para resolução das questões, considere o seguinte esquema:



```
Funcionarios (Codigo, PrimeiroNome,
SegundoNome, UltimoNome,
DataNasci, CPF, RG, Endereco, CEP,
Cidade, Fone, CodigoDepartamento,
Funcao, Salario)

Departamentos (Codigo, Nome,
Localizacao,
CodigoFuncionarioGerente)
```


**Obs: Crie ao menos 10 registros para a tabela Funcionários e ao menos 5 registros para tabela Departamentos.**

A- Listar 	nome e sobrenome ordenado por sobrenome
 	
B- Listar 	todos os campos de funcionários ordenados por cidade
 	
C- Liste 	os funcionários que têm salário superior a R$ 1.000,00 ordenados 	pelo nome completo
 	
D- Liste 	a data de nascimento e o primeiro nome dos funcionários ordenados do mais novo para o mais velho
 	
E- Liste 	o total da folha de pagamento
 	
F- Liste 	o nome, o nome do departamento e a função de todos os funcionários
 	
G- Liste 	a quantidade de funcionários desta empresa
 	
H- Liste 	o nome do departamento e do funcionário ordenados por departamento 	e funcionário

**PARTE 1 - CRIAÇÃO DO BANCO DE DADOS**

1- Criando o banco de dados empresa
"""

import sqlite3
#banco = sqlite.3connect(':memory:')
banco = sqlite3.connect('empresa.db')

#banco criado

"""2-Criando um cursor para operar comandos SQL"""

cursor = banco.cursor()

#feito

"""3-Criando a tabela Colaboradores e seus campos"""

cursor.execute("CREATE TABLE colaboradores(Codigo integer, PrimeiroNome text, SegundoNome text, UltimoNome text, DataNasci integer, CPF integer, RG integer, Endereco text , CEP integer, Cidade text, Fone integer, CodigoDepartamento integer, Funcao text, Salario integer)")

#adicionando dados a tabela
#1
cursor.execute("INSERT INTO colaboradores VALUES(1, 'Paulo', 'Santos', 'Pereira', 10/06/1999, 10, 001, 'rua 1', 83500, 'Curitiba', 1, 1, 'tec informatica n1', 900)")
cursor.execute("INSERT INTO colaboradores VALUES(2, 'Maria', 'Silva', 'Cristo', 15/02/2001, 09, 002, 'rua 20', 83500, 'Curitiba' , 2, 1, 'tec informatica n2', 1300)")
cursor.execute("INSERT INTO colaboradores VALUES(3, 'Wellington', 'Ruan' , 'Coimbra', 19/02/2001, 08, 003, 'rua 30', 83500, 'São Paulo', 3, 2, 'analista de sistema', 980)")
cursor.execute("INSERT INTO colaboradores VALUES(4, 'Dylan', 'Souza', 'Pires', 23/05/2000, 07, 004, 'rua 23', 83500, 'São Paulo', 10, 2, 'Analista de infra' , 1500)")
cursor.execute("INSERT INTO colaboradores VALUES(5, 'Milena', 'Oliveira', 'Assunçao', 15/08/2001, 06, 005, 'rua 25', 83500, 'Recife', 4, 3, 'Noc jr', 990)")
cursor.execute("INSERT INTO colaboradores VALUES(6, 'Cleber', 'Machado', 'Oliveira', 15/04/1992, 05, 006, 'rua 007', 83500, 'Recife', 5, 3, 'Noc senior', 2000)")
cursor.execute("INSERT INTO colaboradores VALUES(7, 'Joao', 'Antonio', 'Santos', 18/02/1991, 04, 007, 'rua 123' , 83500, 'Natal', 6, 4, 'analista de rh', 975)")
cursor.execute("INSERT INTO colaboradores VALUES(8, 'jose', 'Pereira', 'Silva', 30/01/2001, 03, 008, 'rua 304', 83500, 'Natal', 7, 4, 'gerente de rh', 2800)")
cursor.execute("INSERT INTO colaboradores VALUES(9, 'Amanda', 'Alves', 'Costa', 27/02/1998, 02, 009, 'rua 305', 83500, 'Porto Alegre', 8, 5, 'auxiliar adm' , 1000)")
cursor.execute("INSERT INTO colaboradores VALUES(10, 'Felipe', 'Assunçao', 'Santos', 25/11/2002, 010, 030, 'rua 01', 83500, 'Porto Alegre', 9, 5, 'assistente adm pleno' , 1500)")
banco.commit()
#tudo funcionando

"""4-Criando a tabela departamentos e seus campos"""

cursor.execute("CREATE TABLE departamentos(Codigo integer, Nome text, Localizacao text, CodigoFuncionarioGerente interger)")

#adicionando dados a tabela
#1
cursor.execute("INSERT INTO departamentos VALUES(1, 'suporte', 'Curitiba', 1)")
cursor.execute("INSERT INTO departamentos VALUES(2, 'infra', 'São Paulo', 2)")
cursor.execute("INSERT INTO departamentos VALUES(3, 'noc', 'Recife', 3)")
cursor.execute("INSERT INTO departamentos VALUES(4, 'rh', 'Natal', 4)")
cursor.execute("INSERT INTO departamentos VALUES(5, 'adm', 'Porto Alegre', 5)")
banco.commit()
#tudo ok (we are the champions)

"""**PARTE 2 - CONSULTANDO DADOS**

PRIMEIRO IREI TRAZER TODOS OS DADOS QUE FOI ADICIONADO NO BANCO
"""

cursor.execute("SELECT * FROM colaboradores")
print (cursor.fetchall())

cursor.execute("SELECT * FROM departamentos")
print (cursor.fetchall())

"""A- Listar nome e sobrenome ordenado por sobrenome"""

cursor.execute("""SELECT PrimeiroNome, SegundoNome FROM colaboradores ORDER BY SegundoNome""")
print (cursor.fetchall())

"""B- Listar todos os campos de funcionários ordenados por cidade"""

cursor.execute("""SELECT * FROM colaboradores ORDER BY Cidade""")
print (cursor.fetchall())

"""C- Liste os funcionários que têm salário superior a R$ 1.000,00 ordenados pelo nome completo"""

cursor.execute("""SELECT * FROM colaboradores WHERE salario >'1000' ORDER BY Primeironome""")
print (cursor.fetchall())

"""D- Liste a data de nascimento e o primeiro nome dos funcionários ordenados do mais novo para o mais velho"""

cursor.execute("""SELECT DataNasci, PrimeiroNome FROM colaboradores ORDER BY DataNasci DESC""")
print (cursor.fetchall())

"""E- Liste o total da folha de pagamento"""

cursor.execute("""SELECT SUM(Salario) AS TOTAL FROM colaboradores""")
print (cursor.fetchall())

"""F- Liste o nome, o nome do departamento e a função de todos os funcionários"""

cursor.execute("""SELECT F.PrimeiroNome, D.Nome, F.Funcao FROM colaboradores F JOIN departamentos D ON  F.Codigo = D.Codigo ORDER BY F.PrimeiroNome""")
print (cursor.fetchall())

"""G- Liste a quantidade de funcionários desta empresa"""

cursor.execute("""SELECT COUNT(*) AS Totatalcolaboradores FROM colaboradores""")
print (cursor.fetchall())

"""H- Liste o nome do departamento e do funcionário ordenados por departamento e funcionário"""

cursor.execute("""SELECT D.Nome, F.PrimeiroNome FROM departamentos D JOIN colaboradores F ON D.Codigo = F.Codigo ORDER BY D.Nome, F.PrimeiroNome""")
print (cursor.fetchall())